// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fldrdenuwinjymymfnmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZHJkZW51d2luanlteW1mbm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjMwOTMsImV4cCI6MjA2NzE5OTA5M30.y4kzPXFK20_QMuxiSWrtlSPYStQSTr6qxjcX405CLVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});